/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negócio.Cliente;
import Telas.PopUps.Campos_preenchidos;
import Telas.PopUps.Operacao_sucesso;
import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Alexf
 */
public class Altera_cliente extends javax.swing.JFrame {

    /**
     * Creates new form Janela_modelo
     */
    public Altera_cliente() {
        initComponents();
        spinnerId.setVisible(false);
    }
    
    public void setaCampos(String nome, String CPF, String telefone, String email, int id){
        tNomeCliente.setText(nome);
        tCPFCliente.setText(CPF);
        tTelefoneCliente.setText(telefone);
        tEmailCliente.setText(email);
        spinnerId.setValue(id);
        
    }
    
    
    public boolean verificaCampos(){
        boolean verificador = true;
        if(tNomeCliente.getText().length()==0){
            setColorRed(lblNome);
            verificador = false;
        }else{
            setColorBlack(lblNome);
        }
        
        if(tCPFCliente.getText().length()==0){
            setColorRed(lblCPF);
            verificador = false;
        }else{
            setColorBlack(lblCPF);
        }
        
        if(tTelefoneCliente.getText().length()==0){
            setColorRed(lblTelefone);
            verificador = false;
        }else{
            setColorBlack(lblTelefone);
        }
        
        if(tEmailCliente.getText().length()==0){
            setColorRed(lblEmail);
            verificador = false;
        }else{
            setColorBlack(lblEmail);
        }
        
       return verificador;
    }
        
        
    public void setColorRed(JLabel label){
        label.setForeground(Color.red);
    }
    public void setColorBlack(JLabel label){
        label.setForeground(Color.black);
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        painel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tNomeCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        lblNome = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        tCPFCliente = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblTelefone = new javax.swing.JLabel();
        tTelefoneCliente = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        lblEmail = new javax.swing.JLabel();
        tEmailCliente = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        spinnerId = new javax.swing.JSpinner();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_header.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirma-cadastro.png"))); // NOI18N
        jLabel1.setText("Editar Cliente");

        javax.swing.GroupLayout painel_headerLayout = new javax.swing.GroupLayout(painel_header);
        painel_header.setLayout(painel_headerLayout);
        painel_headerLayout.setHorizontalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_headerLayout.setVerticalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelPrincipal.add(painel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 100));

        tNomeCliente.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tNomeCliente.setBorder(null);
        PainelPrincipal.add(tNomeCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 420, 30));
        PainelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 420, 20));

        lblNome.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblNome.setText("Nome:");
        PainelPrincipal.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirma-cadastro.png"))); // NOI18N
        jLabel2.setText("Atualizar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, -1, 58));

        PainelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 500, 320, 80));

        lblCPF.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCPF.setText("CPF:");
        PainelPrincipal.add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        tCPFCliente.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tCPFCliente.setBorder(null);
        PainelPrincipal.add(tCPFCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 420, 30));
        PainelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 280, 420, 20));

        lblTelefone.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblTelefone.setText("Telefone:");
        PainelPrincipal.add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        tTelefoneCliente.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tTelefoneCliente.setBorder(null);
        PainelPrincipal.add(tTelefoneCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 420, 30));
        PainelPrincipal.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 420, 20));

        lblEmail.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblEmail.setText("Email:");
        PainelPrincipal.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, -1, -1));

        tEmailCliente.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tEmailCliente.setBorder(null);
        PainelPrincipal.add(tEmailCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 420, 30));
        PainelPrincipal.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 420, 20));
        PainelPrincipal.add(spinnerId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 640, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if(verificaCampos()){
            String nome = tNomeCliente.getText();
            String CPF = tCPFCliente.getText();
            String email = tEmailCliente.getText();
            String telefone = tTelefoneCliente.getText();
            int id = (int) spinnerId.getValue();
            
            Cliente cliente = new Cliente(nome, email, CPF, telefone, id);
            if(Cliente.alteraCliente(cliente)){
                new Operacao_sucesso().setVisible(true);
                dispose();
                Clientes.preencheTabela();
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao atualizar");
            }
        }else{
            new Campos_preenchidos().setVisible(true);
        }
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setBackground(new Color(22, 43, 229));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setBackground(new Color(45,118,232));
    }//GEN-LAST:event_jPanel1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Altera_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Altera_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Altera_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Altera_cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Altera_cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JPanel painel_header;
    private javax.swing.JSpinner spinnerId;
    private javax.swing.JTextField tCPFCliente;
    private javax.swing.JTextField tEmailCliente;
    private javax.swing.JTextField tNomeCliente;
    private javax.swing.JTextField tTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
