/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negócio.Chamado;
import Negócio.Contrato;
import Telas.PopUps.Erro_linha_invalida;
import Telas.PopUps.perguntaExcluir;
import Telas.PopUps.perguntaExcluirChamado;
import java.awt.Color;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alexf
 */
public class Chamados extends javax.swing.JFrame {
    static int idContrato;
    /**
     * Creates new form Chamados
     */
    public Chamados(int idContrato) {
        initComponents();
        aparenciaTabela();
        this.idContrato = idContrato;
        preencheTabela();
       
    }

    Chamados() {
        initComponents();
    }
    
    public void aparenciaTabela(){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        Tabela.setRowSorter(new TableRowSorter(modelo));
        Tabela.setSelectionBackground(new Color(45,118,232));
        JTableHeader header = Tabela.getTableHeader();
        JScrollPane scroll= jScrollPane1;
        scroll.getViewport().setBackground(Color.WHITE);
    }
    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(22, 43, 229));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(45,118,232));
    }
    
    public static void preencheTabela(){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        
        if(modelo.getRowCount() > 0){
             modelo.setNumRows(0);
        }
        
        ArrayList<Chamado> chamados = Chamado.procuraChamados(idContrato);
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/LLLL/yyyy");
        for(Chamado chamado: chamados){
            
            String dataFormatadaPagamento=null;
            String dataFormatada = chamado.getData().format(formatador);
            String dataFormatadaAtualizacao = chamado.getUltima_atualizacao().format(formatador);
   
            modelo.addRow(new Object[]{
               chamado.getIdChamado(),
               chamado.getMotivo(),
               chamado.getSituacao(),
               dataFormatada,
               dataFormatadaAtualizacao
            });
        }
    }
    public static void preencheTabela(ArrayList<Chamado> chamados){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        
        if(modelo.getRowCount() > 0){
             modelo.setNumRows(0);
        }
        
        DateTimeFormatter formatador = DateTimeFormatter.ofPattern("dd/LLLL/yyyy");
        for(Chamado chamado: chamados){
            
            String dataFormatadaPagamento=null;
            String dataFormatada = chamado.getData().format(formatador);
            String dataFormatadaAtualizacao = chamado.getUltima_atualizacao().format(formatador);
   
            modelo.addRow(new Object[]{
               chamado.getIdChamado(),
               chamado.getMotivo(),
               chamado.getSituacao(),
               dataFormatada,
               dataFormatadaAtualizacao
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painel_header = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRemover = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnNovo = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnAtualizar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        btnPesquisar3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jNumeroContrato = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_header.setBackground(new java.awt.Color(45, 118, 232));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar-contrato.png"))); // NOI18N
        jLabel2.setText("Chamados");

        javax.swing.GroupLayout painel_headerLayout = new javax.swing.GroupLayout(painel_header);
        painel_header.setLayout(painel_headerLayout);
        painel_headerLayout.setHorizontalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addContainerGap(915, Short.MAX_VALUE))
        );
        painel_headerLayout.setVerticalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_headerLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(painel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 90));

        btnRemover.setBackground(new java.awt.Color(45, 118, 232));
        btnRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoverMouseExited(evt);
            }
        });
        btnRemover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        jLabel8.setText("Remover");
        btnRemover.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 150, 50));

        jPanel1.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 239, 70));

        btnNovo.setBackground(new java.awt.Color(45, 118, 232));
        btnNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoMouseExited(evt);
            }
        });
        btnNovo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jLabel9.setText("Novo");
        btnNovo.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 58));

        jPanel1.add(btnNovo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 239, 70));

        btnAtualizar.setBackground(new java.awt.Color(45, 118, 232));
        btnAtualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAtualizarMouseExited(evt);
            }
        });
        btnAtualizar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-edit-property.png"))); // NOI18N
        jLabel10.setText("Atualizar");
        btnAtualizar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jPanel1.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 239, 70));

        Tabela.setFont(new java.awt.Font("Century Gothic", 0, 15)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Motivo", "Situação", "Criação", "Última Atualização"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setPreferredWidth(3);
            Tabela.getColumnModel().getColumn(3).setPreferredWidth(7);
            Tabela.getColumnModel().getColumn(4).setPreferredWidth(7);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, 770, 440));

        btnPesquisar3.setBackground(new java.awt.Color(45, 118, 232));
        btnPesquisar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisar3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisar3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisar3MouseExited(evt);
            }
        });
        btnPesquisar3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jLabel11.setText("Pesquisar");
        btnPesquisar3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 58));

        jPanel1.add(btnPesquisar3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 239, 80));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Número do Chamado:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, 20));

        jNumeroContrato.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jNumeroContrato.setBorder(null);
        jPanel1.add(jNumeroContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, 240, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 450, 240, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 592, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseClicked
        if(Tabela.getSelectedRow()!=-1){
            int idChamado = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
            perguntaExcluirChamado tela = new perguntaExcluirChamado(idChamado);
            tela.setVisible(true);
        }else{
           new Erro_linha_invalida().setVisible(true);
        }
    }//GEN-LAST:event_btnRemoverMouseClicked

    private void btnRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseEntered
        setColor(btnRemover);
    }//GEN-LAST:event_btnRemoverMouseEntered

    private void btnRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseExited
        resetColor(btnRemover);
    }//GEN-LAST:event_btnRemoverMouseExited

    private void btnNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseClicked
          
               Novo_chamado tela = new Novo_chamado(idContrato);
               tela.setVisible(true);
           
//               JOptionPane.showMessageDialog(null, "Linha inválida");
           
            
    }//GEN-LAST:event_btnNovoMouseClicked

    private void btnNovoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseEntered
        setColor(btnNovo);
    }//GEN-LAST:event_btnNovoMouseEntered

    private void btnNovoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoMouseExited
        resetColor(btnNovo);
    }//GEN-LAST:event_btnNovoMouseExited

    private void btnAtualizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseClicked
        if(Tabela.getSelectedRow()!=-1){
            String motivo = (String) Tabela.getValueAt(Tabela.getSelectedRow(), 1);
            String situacao = (String) Tabela.getValueAt(Tabela.getSelectedRow(), 2);
            int id = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
            Altera_chamado tela = new Altera_chamado(motivo, situacao, id, idContrato);
            tela.setVisible(true);
        }else{
            new Erro_linha_invalida().setVisible(true);
        }
    }//GEN-LAST:event_btnAtualizarMouseClicked

    private void btnAtualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseEntered
        setColor(btnAtualizar);
    }//GEN-LAST:event_btnAtualizarMouseEntered

    private void btnAtualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAtualizarMouseExited
        resetColor(btnAtualizar);
    }//GEN-LAST:event_btnAtualizarMouseExited

    private void btnPesquisar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisar3MouseClicked
        if(jNumeroContrato.getText().length()==0){
            preencheTabela();
        }else{
            int numeroContrato = Integer.parseInt(jNumeroContrato.getText());
            ArrayList<Chamado> chamados = new ArrayList<>();
            chamados = Chamado.procuraChamados(idContrato, numeroContrato);
            preencheTabela(chamados);
            jNumeroContrato.setText("");
            
        }
    }//GEN-LAST:event_btnPesquisar3MouseClicked

    private void btnPesquisar3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisar3MouseEntered
        setColor(btnPesquisar3);
    }//GEN-LAST:event_btnPesquisar3MouseEntered

    private void btnPesquisar3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisar3MouseExited
        resetColor(btnPesquisar3);
    }//GEN-LAST:event_btnPesquisar3MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chamados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chamados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabela;
    private javax.swing.JPanel btnAtualizar;
    private javax.swing.JPanel btnNovo;
    private javax.swing.JPanel btnPesquisar3;
    private javax.swing.JPanel btnRemover;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNumeroContrato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel painel_header;
    // End of variables declaration//GEN-END:variables
}
