/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Banco.CategoriaDAO;
import Negócio.Canal;
import Negócio.Categoria;
import Telas.PopUps.Campos_preenchidos;
import Telas.PopUps.Operacao_sucesso;
import java.awt.Color;
import static java.lang.Float.parseFloat;
import javax.swing.JOptionPane;
import java.lang.NullPointerException;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Objects;
import javax.swing.JFormattedTextField;
import javax.swing.JSpinner;

/**
 *
 * @author Alexf
 */
public class Novo_canal extends javax.swing.JFrame {

    /**
     * Creates new form Janela_modelo
     */
    public Novo_canal() {
        initComponents();
        setaCategorias();
 
    }
    
    public boolean verificaCampos(){
        boolean habilitado = true;
        if(tNomeCanal.getText().length()==0){
            habilitado = false;
            lblNomeCanal.setForeground(Color.red);
        }else{
            lblNomeCanal.setForeground(Color.black);
        }
        if(jCategoria.getSelectedIndex()==0){
            habilitado = false;
            lblCategoria.setForeground(Color.red);
        }else{
            lblCategoria.setForeground(Color.black);
        }
        if(tPrecoBase.getText().length()==0){
            habilitado = false;
            lblPrecoBase.setForeground(Color.red);
        }else{
            lblPrecoBase.setForeground(Color.black);
        }
        return habilitado;
    }
    
    public void setaCategorias(){
        CategoriaDAO dao = new CategoriaDAO();
        ArrayList<Categoria> categorias = (ArrayList<Categoria>) dao.buscarTodasCategorias();
        for(Categoria categoria: categorias ){
            jCategoria.addItem(categoria.getNome());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelPrincipal = new javax.swing.JPanel();
        painel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tPrecoBase = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblPrecoBase = new javax.swing.JLabel();
        lblCategoria = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblNomeCanal = new javax.swing.JLabel();
        jCategoria = new javax.swing.JComboBox<>();
        jClassEtaria = new javax.swing.JSpinner();
        tNomeCanal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_header.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/canal-pequeno.png"))); // NOI18N
        jLabel1.setText("Cadastrar Novo Canal");

        javax.swing.GroupLayout painel_headerLayout = new javax.swing.GroupLayout(painel_header);
        painel_header.setLayout(painel_headerLayout);
        painel_headerLayout.setHorizontalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painel_headerLayout.setVerticalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelPrincipal.add(painel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1110, 100));

        tPrecoBase.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tPrecoBase.setBorder(null);
        tPrecoBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPrecoBaseActionPerformed(evt);
            }
        });
        tPrecoBase.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tPrecoBaseKeyTyped(evt);
            }
        });
        PainelPrincipal.add(tPrecoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 420, 30));
        PainelPrincipal.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 420, 420, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Classificação Etária:");
        PainelPrincipal.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, -1, -1));

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/canal-pequeno.png"))); // NOI18N
        jLabel2.setText("Cadastrar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        PainelPrincipal.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 530, 320, 80));

        lblPrecoBase.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblPrecoBase.setText("Preço Base:");
        PainelPrincipal.add(lblPrecoBase, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, -1, -1));

        lblCategoria.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblCategoria.setText("Categoria:");
        PainelPrincipal.add(lblCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 220, -1, -1));
        PainelPrincipal.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 420, 20));

        lblNomeCanal.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblNomeCanal.setText("Nome:");
        PainelPrincipal.add(lblNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, -1, -1));

        jCategoria.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jCategoria.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        PainelPrincipal.add(jCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 250, 120, 50));

        jClassEtaria.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jClassEtaria.setModel(new javax.swing.SpinnerNumberModel(0, 0, 18, 1));
        PainelPrincipal.add(jClassEtaria, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 250, 110, 50));

        tNomeCanal.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tNomeCanal.setBorder(null);
        PainelPrincipal.add(tNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 420, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked
        if(verificaCampos()){
            String nome = tNomeCanal.getText();
            int idCategoria = jCategoria.getSelectedIndex();
            int classEtaria = (int) jClassEtaria.getValue();
            float precoBase = Float.parseFloat(tPrecoBase.getText());
            
            Canal canal = new Canal(nome, classEtaria, precoBase, idCategoria);
            if(Canal.adicionarCanal(canal)){
                tNomeCanal.setText("");
                jCategoria.setSelectedIndex(0);
                jClassEtaria.setValue(new Integer(0));
                tPrecoBase.setText("");
                new Operacao_sucesso().setVisible(true);
            }else{
                JOptionPane.showMessageDialog(null, "Erro ao adicionar o canal!");
            };
            Canais.preencherTabela(); 
        }else{
            new Campos_preenchidos().setVisible(true);
        }
                   
    }//GEN-LAST:event_jPanel1MouseClicked

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setBackground(new Color(22, 43, 229));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setBackground(new Color(45,118,232));
    }//GEN-LAST:event_jPanel1MouseExited

    private void tPrecoBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPrecoBaseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tPrecoBaseActionPerformed

    private void tPrecoBaseKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPrecoBaseKeyTyped
       
    }//GEN-LAST:event_tPrecoBaseKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Novo_canal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Novo_canal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Novo_canal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Novo_canal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Novo_canal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    private javax.swing.JComboBox<String> jCategoria;
    private javax.swing.JSpinner jClassEtaria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblCategoria;
    private javax.swing.JLabel lblNomeCanal;
    private javax.swing.JLabel lblPrecoBase;
    private javax.swing.JPanel painel_header;
    private javax.swing.JTextField tNomeCanal;
    private javax.swing.JTextField tPrecoBase;
    // End of variables declaration//GEN-END:variables
}
