/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negócio.Cliente;
import Negócio.Contrato;
import Telas.PopUps.Erro_cpf;
import Telas.PopUps.Erro_linha_invalida;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alexf
 */
public class Procura_contratos_chamado extends javax.swing.JFrame {

    /**
     * Creates new form Chamados
     */
    public Procura_contratos_chamado() {
        initComponents();
        aparenciaTabela();
        lblCliente.setVisible(false);
        lblNomeCliente.setVisible(false);
        jCPFCliente.requestFocus();
    }
    
    public void aparenciaTabela(){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        Tabela.setRowSorter(new TableRowSorter(modelo));
        Tabela.setSelectionBackground(new Color(45,118,232));
        JTableHeader header = Tabela.getTableHeader();
        JScrollPane scroll= jScrollPane1;
        scroll.getViewport().setBackground(Color.WHITE);
    }
        
    public void setColor(JPanel panel){
        panel.setBackground(new Color(22, 43, 229));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(45,118,232));
    }
    
    public static void preencheTabela(ArrayList<Contrato> contratos){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        if(modelo.getRowCount()>0)
            modelo.setRowCount(0);
        
        for(Contrato contrato: contratos){
            String acesso = "";
            if(contrato.getAcesso()==1){
                acesso = "Habilitado";
            }else{
                acesso = "Desabilitado";
            }
            modelo.addRow(new Object[]{
                contrato.getIdContrato(),
                contrato.getNomePlano(),
                contrato.getQuantReceptores(),
                contrato.getEndCobranca(),
                acesso,
                contrato.getIdPlano()
            });
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painel_header = new javax.swing.JPanel();
        lblCliente = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblNomeCliente = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jCPFCliente = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        btnPesquisar1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_header.setBackground(new java.awt.Color(45, 118, 232));

        lblCliente.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario-pequeno.png"))); // NOI18N
        lblCliente.setText("Cliente:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/procurar-contrato.png"))); // NOI18N
        jLabel2.setText("Procurar Contrato");

        lblNomeCliente.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblNomeCliente.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout painel_headerLayout = new javax.swing.GroupLayout(painel_header);
        painel_header.setLayout(painel_headerLayout);
        painel_headerLayout.setHorizontalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel2)
                .addGap(95, 95, 95)
                .addComponent(lblCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNomeCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 508, Short.MAX_VALUE)
                .addContainerGap())
        );
        painel_headerLayout.setVerticalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_headerLayout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_headerLayout.createSequentialGroup()
                        .addComponent(lblNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8))
                    .addGroup(painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        jPanel1.add(painel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 90));

        btnPesquisar.setBackground(new java.awt.Color(45, 118, 232));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseExited(evt);
            }
        });
        btnPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jLabel8.setText("Pesquisar");
        btnPesquisar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 58));

        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, 239, 80));

        jCPFCliente.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jCPFCliente.setBorder(null);
        jPanel1.add(jCPFCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 240, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 240, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("CPF do Cliente:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, 20));

        btnPesquisar1.setBackground(new java.awt.Color(45, 118, 232));
        btnPesquisar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisar1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisar1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisar1MouseExited(evt);
            }
        });
        btnPesquisar1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ver-chamados.png"))); // NOI18N
        jLabel9.setText("Abrir Painel");
        btnPesquisar1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 58));

        jPanel1.add(btnPesquisar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 150, 240, 80));

        Tabela.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Plano", "Receptores", "Endereço", "Acesso", "idPlano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(5).setMinWidth(0);
            Tabela.getColumnModel().getColumn(5).setPreferredWidth(0);
            Tabela.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 120, 680, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        if(jCPFCliente.getText().length() == 0){
            new Erro_cpf().setVisible(true);
            lblCliente.setVisible(false);
            lblNomeCliente.setVisible(false);
            jCPFCliente.setText("");
            preencheTabela(new ArrayList<>());
        }else {
            String CPF = jCPFCliente.getText();
            Cliente c = Cliente.buscaUmCliente(CPF);
            lblCliente.setVisible(true);
            lblNomeCliente.setText(c.getNome());
            lblNomeCliente.setVisible(true);
            ArrayList<Contrato> contratos = Contrato.devolveContratos(c.getIdCliente());
            preencheTabela(contratos);
            jCPFCliente.setText("");
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        setColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void btnPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseExited
        resetColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseExited

    private void btnPesquisar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisar1MouseClicked
        if(Tabela.getSelectedRow()!=-1){
           int idContrato = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
           Chamados tela = new Chamados(idContrato);
           tela.setVisible(true);  
        }else{
            new Erro_linha_invalida().setVisible(true);
        }

           
      
    }//GEN-LAST:event_btnPesquisar1MouseClicked

    private void btnPesquisar1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisar1MouseEntered
        setColor(btnPesquisar1);
    }//GEN-LAST:event_btnPesquisar1MouseEntered

    private void btnPesquisar1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisar1MouseExited
        resetColor(btnPesquisar1);
    }//GEN-LAST:event_btnPesquisar1MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Procura_contratos_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Procura_contratos_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Procura_contratos_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Procura_contratos_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Procura_contratos_chamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabela;
    private javax.swing.JPanel btnPesquisar;
    private javax.swing.JPanel btnPesquisar1;
    private javax.swing.JTextField jCPFCliente;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JPanel painel_header;
    // End of variables declaration//GEN-END:variables
}
