/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Telas.PopUps.perguntaExcluir;
import Telas.PopUps.Error_atualização_canal;
import Negócio.Canal;
import Telas.PopUps.Error_exclusão_canal;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alexf
 */
public class Canais extends javax.swing.JFrame {

    /**
     * Creates new form Janela_modelo
     */
    public Canais() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        Tabela.setRowSorter(new TableRowSorter(modelo));
        Tabela.setSelectionBackground(new Color(45,118,232));
        JTableHeader header = Tabela.getTableHeader();
        //Tabela.setRowSorter(new TableRowSorter(modelo));
        
        JScrollPane scroll= jScrollPane2;
        scroll.getViewport().setBackground(Color.WHITE);

        preencherTabela();
        
    }
    
    public static void preencherTabela(ArrayList<Canal> canais){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        
        if(modelo.getRowCount() > 0){
             modelo.setNumRows(0);
        }
        
        for(Canal canal : canais){
            modelo.addRow(new Object[]{
                canal.getNome(),
                canal.getNumero(),
                canal.getClassEtaria(),
                canal.getPrecoBase(),
                canal.getNomeCategoria()
            });
        }
    }
    
    public static void preencherTabela(){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        
        if(modelo.getRowCount() > 0){
             modelo.setNumRows(0);
        }
        
        ArrayList<Canal> canais = Canal.buscarCanais();
        for(Canal canal : canais){
            modelo.addRow(new Object[]{
                canal.getNome(),
                canal.getNumero(),
                canal.getClassEtaria(),
                canal.getPrecoBase(),
                canal.getNomeCategoria()
            });
        }
    }
    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(22, 43, 229));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(45,118,232));
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        PainelPrincipal = new javax.swing.JPanel();
        painel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        btnAlterar = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btnRemover = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jNomeCanal = new javax.swing.JTextField();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelPrincipal.setBackground(new java.awt.Color(255, 255, 255));
        PainelPrincipal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_header.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/canal-pequeno.png"))); // NOI18N
        jLabel1.setText("Lista de Canais");

        javax.swing.GroupLayout painel_headerLayout = new javax.swing.GroupLayout(painel_header);
        painel_header.setLayout(painel_headerLayout);
        painel_headerLayout.setHorizontalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel1)
                .addContainerGap(920, Short.MAX_VALUE))
        );
        painel_headerLayout.setVerticalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        PainelPrincipal.add(painel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1180, 100));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Tabela.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Número", "Classificação Etária", "Preço Base", "Categoria"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        Tabela.setGridColor(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(0).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setResizable(false);
            Tabela.getColumnModel().getColumn(1).setPreferredWidth(7);
            Tabela.getColumnModel().getColumn(2).setResizable(false);
            Tabela.getColumnModel().getColumn(2).setPreferredWidth(5);
            Tabela.getColumnModel().getColumn(3).setResizable(false);
            Tabela.getColumnModel().getColumn(3).setPreferredWidth(10);
            Tabela.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(2, 7, 860, 520));

        PainelPrincipal.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, 860, 570));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAlterar.setBackground(new java.awt.Color(45, 118, 232));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-edit-property.png"))); // NOI18N
        jLabel2.setText("Editar");
        btnAlterar.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 58));

        jPanel3.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 239, 80));

        btnRemover.setBackground(new java.awt.Color(45, 118, 232));
        btnRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRemoverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoverMouseExited(evt);
            }
        });
        btnRemover.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        jLabel6.setText("Remover");
        btnRemover.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, 58));

        jPanel3.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 239, 80));

        btnPesquisar.setBackground(new java.awt.Color(45, 118, 232));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseExited(evt);
            }
        });
        btnPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jLabel8.setText("Pesquisar");
        btnPesquisar.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 58));

        jPanel3.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 450, 239, 80));

        btnCadastrar.setBackground(new java.awt.Color(45, 118, 232));
        btnCadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCadastrarMouseExited(evt);
            }
        });
        btnCadastrar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jLabel9.setText("Cadastrar");
        btnCadastrar.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 58));

        jPanel3.add(btnCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 239, 80));
        jPanel3.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 240, 20));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Nome do Canal:");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, -1, -1));

        jNomeCanal.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jNomeCanal.setBorder(null);
        jPanel3.add(jNomeCanal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 240, 40));

        PainelPrincipal.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 280, 560));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        resetColor(btnAlterar);
    }//GEN-LAST:event_btnAlterarMouseExited

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        setColor(btnAlterar);
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
       if( Tabela.getSelectedRow() != -1){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
           
        String nome = (String) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
        int numero = (int) Tabela.getValueAt(Tabela.getSelectedRow(),1);
        int classEtaria = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 2);
        float precoBase = (float) Tabela.getValueAt(Tabela.getSelectedRow(), 3);
        String nomeCategoria = (String) Tabela.getValueAt(Tabela.getSelectedRow(), 4);
        int idCategoria = 0;
           System.out.println(nomeCategoria);
           //nomeCategoria = nomeCategoria.substring(0, 7);
           System.out.println(nomeCategoria);
           
        
        if(nomeCategoria.equals("Infantil")){
            idCategoria = 1;
        }else if(nomeCategoria.equals("Filme")){
            idCategoria = 2;
        }else if(nomeCategoria.equals("Notícia")){
            idCategoria = 3;
        }else if(nomeCategoria.equals("Esporte")){
            idCategoria = 4;
        }

        new Altera_canal().setVisible(true);
        Altera_canal.tNomeCanal.setText(nome);
//        Altera_canal.numero.setValue(numero);
        Altera_canal.tNumero.setText(Integer.toString(numero));
//        Altera_canal.numero.setEnabled(false);
        Altera_canal.classEtaria.setValue(classEtaria);
        Altera_canal.tPrecoBase.setText(Float.toString(precoBase));
        Altera_canal.categoria.setSelectedIndex(idCategoria);
        
       }else{
           new Error_atualização_canal().setVisible(true);
       }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseClicked

        //Criando popup de exclusão de canal e tornando-a visível
        if(Tabela.getSelectedRow() != -1){ //verificando se existe alguma linha selecionada.
            perguntaExcluir jPerguntaExcluir = new perguntaExcluir(Tabela);
            jPerguntaExcluir.setVisible(true);
        }else{
           new Error_exclusão_canal().setVisible(true);
       }
    }//GEN-LAST:event_btnRemoverMouseClicked

    private void btnRemoverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseEntered
        setColor(btnRemover);
    }//GEN-LAST:event_btnRemoverMouseEntered

    private void btnRemoverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoverMouseExited
        resetColor(btnRemover);
    }//GEN-LAST:event_btnRemoverMouseExited

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        if(jNomeCanal.getText().length() == 0){
            preencherTabela();
        }else {
            String nomeCanal = jNomeCanal.getText();
            ArrayList<Canal> canais = Canal.buscaCanal(nomeCanal);
            preencherTabela(canais);
            jNomeCanal.setText("");
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        setColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void btnPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseExited
        resetColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseExited

    private void btnCadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseClicked
        new Novo_canal().setVisible(true);
    }//GEN-LAST:event_btnCadastrarMouseClicked

    private void btnCadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseEntered
        setColor(btnCadastrar);
    }//GEN-LAST:event_btnCadastrarMouseEntered

    private void btnCadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCadastrarMouseExited
        resetColor(btnCadastrar);
    }//GEN-LAST:event_btnCadastrarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Canais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Canais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Canais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Canais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Canais().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PainelPrincipal;
    public static javax.swing.JTable Tabela;
    private javax.swing.JPanel btnAlterar;
    private javax.swing.JPanel btnCadastrar;
    private javax.swing.JPanel btnPesquisar;
    private javax.swing.JPanel btnRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JTextField jNomeCanal;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel painel_header;
    // End of variables declaration//GEN-END:variables
}
