/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negócio.Chamado;
import Negócio.Contrato;
import Telas.PopUps.Campos_preenchidos;
import Telas.PopUps.Operacao_sucesso;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Alexf
 */
public class Novo_chamado extends javax.swing.JFrame {
    Contrato contrato;
    int idContrato;
    /**
     * Creates new form Novo_chamado
     */
    public Novo_chamado(int idContrato) {
        initComponents();
        this.idContrato = idContrato;
        jComboBoxSituacao.setBackground(Color.white);
        this.contrato = Contrato.devolveContrato(idContrato);
        lblContrato.setText(Integer.toString(idContrato));
    }

    private Novo_chamado() {
        initComponents();
        jComboBoxSituacao.setBackground(Color.white);
    }
    
    public boolean verificaCampo(){
        boolean habilitado = true;
        if(jComboBoxSituacao.getSelectedIndex()==0){
            habilitado = false;
            lblSituacao.setForeground(Color.RED);
        }else{
           lblSituacao.setForeground(Color.black);
        }
        if(tMotivo.getText().length()==0){
            habilitado = false;
            lblMotivo.setForeground(Color.RED);
        }else{
            lblMotivo.setForeground(Color.black);
        }
        return habilitado;
    }
    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(22, 43, 229));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(45,118,232));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        painel_header = new javax.swing.JPanel();
        lblContrato = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tMotivo = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        lblMotivo = new javax.swing.JLabel();
        lblSituacao = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jComboBoxSituacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_header.setBackground(new java.awt.Color(45, 118, 232));

        lblContrato.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblContrato.setForeground(new java.awt.Color(255, 255, 255));
        lblContrato.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblContrato.setText("numero");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ver-chamados.png"))); // NOI18N
        jLabel3.setText("Novo Chamado");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/contrato-pequeno.png"))); // NOI18N
        jLabel4.setText("Contrato nº :");

        javax.swing.GroupLayout painel_headerLayout = new javax.swing.GroupLayout(painel_header);
        painel_header.setLayout(painel_headerLayout);
        painel_headerLayout.setHorizontalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_headerLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblContrato)
                .addGap(365, 365, 365))
        );
        painel_headerLayout.setVerticalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContrato, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jPanel2.add(painel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 90));

        tMotivo.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        tMotivo.setBorder(null);
        jPanel2.add(tMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 1000, 30));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 1000, 20));

        lblMotivo.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblMotivo.setText("Motivo:");
        jPanel2.add(lblMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lblSituacao.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        lblSituacao.setText("Situação:");
        jPanel2.add(lblSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jPanel1.setBackground(new java.awt.Color(45, 118, 232));
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel1MouseExited(evt);
            }
        });
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/novo-contrato.png"))); // NOI18N
        jLabel5.setText("Registrar");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanel2.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 320, 80));

        jComboBoxSituacao.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jComboBoxSituacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione", "Em Aberto", "Solicitada Manuntenção no Local", "Visita Técnica Marcada", "Técnico Enviado Ao Local", "Concluído", "Cancelado" }));
        jPanel2.add(jComboBoxSituacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 1010, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 476, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseExited
        jPanel1.setBackground(new Color(45,118,232));
    }//GEN-LAST:event_jPanel1MouseExited

    private void jPanel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseEntered
        jPanel1.setBackground(new Color(22, 43, 229));
    }//GEN-LAST:event_jPanel1MouseEntered

    private void jPanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseClicked

    if(verificaCampo()){
       String motivo =tMotivo.getText();
        String situacao = (String) jComboBoxSituacao.getSelectedItem();
        int idContrato = this.contrato.getIdContrato();
        int idPlano = this.contrato.getIdPlano();
        int idCliente = this.contrato.getIdCliente();

        Chamado c  = new Chamado(situacao, motivo, idCliente, idPlano, idContrato);
        if(Chamado.adicionaChamado(c)){
            Chamados.preencheTabela();
            dispose();
            new Operacao_sucesso().setVisible(true);
        }else{
            dispose();
            JOptionPane.showMessageDialog(null, "falhar ao incluir");
        }  
    }else{
        new Campos_preenchidos().setVisible(true);
    }
        

    }//GEN-LAST:event_jPanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Novo_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Novo_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Novo_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Novo_chamado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Novo_chamado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxSituacao;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblMotivo;
    private javax.swing.JLabel lblSituacao;
    private javax.swing.JPanel painel_header;
    private javax.swing.JTextField tMotivo;
    // End of variables declaration//GEN-END:variables
}
