/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Negócio.Categoria;
import Negócio.Chamado;
import Negócio.Contrato;
import Negócio.Pagamento;
import static Telas.Clientes.Tabela;
import Telas.PopUps.Erro_chamado_aberto;
import Telas.PopUps.Erro_linha_invalida;
import Telas.PopUps.Fatura_aberto;
import Telas.PopUps.perguntaExcluirContrato;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alexf
 */
public class Perfil_clientes extends javax.swing.JFrame {

    /**
     * Creates new form Perfil_clientes
     */
    public Perfil_clientes(String nome, String CPF, int id) {
        initComponents();
        
        lblId.setVisible(false);
        lblId.setText(Integer.toString(id));
        System.out.println("o id é " + id);
        lblNome.setText(nome);
        lblCPF.setText(CPF);
        aparenciaTabela();
        preencheTabela();
        
    }

    Perfil_clientes() {
        initComponents();
    }
    
    public void aparenciaTabela(){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        Tabela.setRowSorter(new TableRowSorter(modelo));
        Tabela.setSelectionBackground(new Color(45,118,232));
        JTableHeader header = Tabela.getTableHeader();
        JScrollPane scroll= jScrollPane1;
        scroll.getViewport().setBackground(Color.WHITE);
    }
    
    public static void preencheTabela(){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        if(modelo.getRowCount()>0)
            modelo.setRowCount(0);
        
        ArrayList<Contrato> contratos = new ArrayList<>();
        contratos = Contrato.devolveContratos(Integer.parseInt(lblId.getText()));
        
        for(Contrato contrato: contratos){
            String acesso = "";
            if(contrato.getAcesso()==1){
                acesso = "Habilitado";
            }else{
                acesso = "Desabilitado";
            }
            modelo.addRow(new Object[]{
                contrato.getIdContrato(),
                contrato.getNomePlano(),
                contrato.getQuantReceptores(),
                contrato.getEndCobranca(),
                acesso,
                contrato.getIdPlano()
            });
        }
    }
    
    public static void preencheTabela(ArrayList<Contrato> contratos){
        DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
        if(modelo.getRowCount()>0)
            modelo.setRowCount(0);
        
        for(Contrato contrato: contratos){
            String acesso = "";
            if(contrato.getAcesso()==1){
                acesso = "Habilitado";
            }else{
                acesso = "Desabilitado";
            }
            modelo.addRow(new Object[]{
                contrato.getIdContrato(),
                contrato.getNomePlano(),
                contrato.getQuantReceptores(),
                contrato.getEndCobranca(),
                acesso,
                contrato.getIdPlano()
            });
        }
    }
    
    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(22, 43, 229));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(45,118,232));
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        painel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblId = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabela = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btnInformacoes = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btnPesquisar = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        btnNovoContrato = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jNumeroContrato = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btnAlterar = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel1.setPreferredSize(new java.awt.Dimension(1100, 720));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_header.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente-perfil.png"))); // NOI18N
        jLabel1.setText("Perfil de:");

        lblCPF.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCPF.setText("TesteCpf");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cpf1.png"))); // NOI18N
        jLabel5.setText("Cpf:");

        lblNome.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        lblNome.setForeground(new java.awt.Color(255, 255, 255));
        lblNome.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNome.setText("TesteNome");

        lblId.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        lblId.setForeground(new java.awt.Color(255, 255, 255));
        lblId.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblId.setText("testeid");

        javax.swing.GroupLayout painel_headerLayout = new javax.swing.GroupLayout(painel_header);
        painel_header.setLayout(painel_headerLayout);
        painel_headerLayout.setHorizontalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_headerLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNome, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
                .addGap(2, 2, 2)
                .addComponent(jLabel5)
                .addGap(1, 1, 1)
                .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblId, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
        );
        painel_headerLayout.setVerticalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGroup(painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painel_headerLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblNome, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(painel_headerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblId)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(painel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1270, 100));

        Tabela.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        Tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número", "Plano", "Receptores", "Endereço", "Acesso", "idPlano"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(Tabela);
        if (Tabela.getColumnModel().getColumnCount() > 0) {
            Tabela.getColumnModel().getColumn(5).setMinWidth(0);
            Tabela.getColumnModel().getColumn(5).setPreferredWidth(0);
            Tabela.getColumnModel().getColumn(5).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, 920, 490));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(45, 118, 232));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Contratos");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, -1, 58));

        btnInformacoes.setBackground(new java.awt.Color(45, 118, 232));
        btnInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInformacoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInformacoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInformacoesMouseExited(evt);
            }
        });
        btnInformacoes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/informacoes-contrato.png"))); // NOI18N
        jLabel9.setText("Informações");
        btnInformacoes.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jPanel1.add(btnInformacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 239, 70));

        btnPesquisar.setBackground(new java.awt.Color(45, 118, 232));
        btnPesquisar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnPesquisarMouseExited(evt);
            }
        });
        btnPesquisar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/search.png"))); // NOI18N
        jLabel10.setText("Pesquisar");
        btnPesquisar.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, 50));

        jPanel1.add(btnPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 239, 70));

        btnNovoContrato.setBackground(new java.awt.Color(45, 118, 232));
        btnNovoContrato.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNovoContratoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNovoContratoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNovoContratoMouseExited(evt);
            }
        });
        btnNovoContrato.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/add.png"))); // NOI18N
        jLabel11.setText("Novo Contrato");
        btnNovoContrato.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jPanel1.add(btnNovoContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 239, 70));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 560, 240, 20));

        jNumeroContrato.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jNumeroContrato.setBorder(null);
        jPanel1.add(jNumeroContrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, 240, 40));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setText("Número do Contrato:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, -1, -1));

        btnAlterar.setBackground(new java.awt.Color(45, 118, 232));
        btnAlterar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAlterarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAlterarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAlterarMouseExited(evt);
            }
        });
        btnAlterar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8-edit-property.png"))); // NOI18N
        jLabel14.setText("Alterar");
        btnAlterar.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jPanel1.add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 239, 70));

        btnCancelar.setBackground(new java.awt.Color(45, 118, 232));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCancelarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCancelarMouseExited(evt);
            }
        });
        btnCancelar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/remove.png"))); // NOI18N
        jLabel13.setText("Cancelar");
        btnCancelar.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 50));

        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 239, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1270, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacoesMouseClicked
       if(Tabela.getSelectedRow()!= -1){
          DefaultTableModel modelo = (DefaultTableModel) Tabela.getModel();
          int idContrato =  (int) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
          String lblPlano = (String) Tabela.getValueAt(Tabela.getSelectedRow(), 1);
          int lblQuantReceptores = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 2);
          String lblEndCobranca = (String) Tabela.getValueAt(Tabela.getSelectedRow(), 3);
          String lblAcesso = (String) Tabela.getValueAt(Tabela.getSelectedRow(), 4);
          int idPlano = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 5);
          int idCliente = Integer.parseInt(lblId.getText());
          String nome = lblNome.getText();
          
          new Informacao_contrato(idContrato, lblAcesso, lblEndCobranca, lblQuantReceptores, lblPlano, idPlano, idCliente,nome).setVisible(true); ;
       }else{
           new Erro_linha_invalida().setVisible(true);
       }
       
    }//GEN-LAST:event_btnInformacoesMouseClicked

    private void btnInformacoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacoesMouseEntered
        setColor(btnInformacoes);
    }//GEN-LAST:event_btnInformacoesMouseEntered

    private void btnInformacoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInformacoesMouseExited
        resetColor(btnInformacoes);
    }//GEN-LAST:event_btnInformacoesMouseExited

    private void btnPesquisarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseClicked
        if(jNumeroContrato.getText().length()==0){
            preencheTabela();
        }else{
            int numeroContrato = Integer.parseInt(jNumeroContrato.getText());
            ArrayList<Contrato> contratos = new ArrayList<>();
            Contrato c = Contrato.devolveContrato(numeroContrato);
            contratos.add(c);
            preencheTabela(contratos);
            jNumeroContrato.setText("");
        }
    }//GEN-LAST:event_btnPesquisarMouseClicked

    private void btnPesquisarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseEntered
        setColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseEntered

    private void btnPesquisarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPesquisarMouseExited
        resetColor(btnPesquisar);
    }//GEN-LAST:event_btnPesquisarMouseExited

    private void btnNovoContratoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoContratoMouseClicked
        new Novo_contrato(lblId.getText(),Tabela).setVisible(true);
    }//GEN-LAST:event_btnNovoContratoMouseClicked

    private void btnNovoContratoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoContratoMouseEntered
        setColor(btnNovoContrato);
    }//GEN-LAST:event_btnNovoContratoMouseEntered

    private void btnNovoContratoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNovoContratoMouseExited
        resetColor(btnNovoContrato);
    }//GEN-LAST:event_btnNovoContratoMouseExited

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        if(Tabela.getSelectedRow()!=-1){
            int idContrato = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
            ArrayList<Pagamento> pagamentos = Pagamento.buscaFaturasCancelamento(idContrato);
            boolean habilitado=true;
            for(Pagamento pagamento: pagamentos){
                if(pagamento.getPago()==0){
                    habilitado = false;
                    
                }
            }
            if(habilitado==false){
                new Fatura_aberto().setVisible(true);
            }
            ArrayList<Chamado> chamados = Chamado.procuraChamados(idContrato);
            if(chamados.size()>0){
                habilitado = false;
                new Erro_chamado_aberto().setVisible(true);
            }
            
            if(habilitado){
                 perguntaExcluirContrato tela = new perguntaExcluirContrato(idContrato, Tabela);
                 tela.setVisible(true);
            }
        }else{
            new Erro_linha_invalida().setVisible(true);
        }
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnCancelarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseEntered
        setColor(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseEntered

    private void btnCancelarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseExited
        resetColor(btnCancelar);
    }//GEN-LAST:event_btnCancelarMouseExited

    private void btnAlterarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseClicked
        if(Tabela.getSelectedRow()!=-1){
            int idContrato = (int) Tabela.getValueAt(Tabela.getSelectedRow(), 0);
            ArrayList<Pagamento> pagamentos = Pagamento.buscaFaturasCancelamento(idContrato);
            boolean habilitado=true;
            for(Pagamento pagamento: pagamentos){
                if(pagamento.getPago()==0){
                    habilitado = false;
                }
            }
            if(habilitado==false){
                new Fatura_aberto().setVisible(true);
            }
            ArrayList<Chamado> chamados = Chamado.procuraChamados(idContrato);
            if(chamados.size()>0){
                habilitado = false;
                new Erro_chamado_aberto().setVisible(true);
            }
            
            
            if(habilitado){
                ArrayList<Categoria> categorias = Contrato.devolveCategoriasContrato(idContrato);
                Contrato c = Contrato.devolveContrato(idContrato);
                Altera_contrato tela = new Altera_contrato(lblId.getText(), c.getEndCobranca(), c.getIdPlano(), categorias, c.getQuantReceptores(),idContrato);
                tela.setVisible(true);
            }
        }else{
            new Erro_linha_invalida().setVisible(true);
        }
    }//GEN-LAST:event_btnAlterarMouseClicked

    private void btnAlterarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseEntered
        setColor(btnAlterar);
    }//GEN-LAST:event_btnAlterarMouseEntered

    private void btnAlterarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAlterarMouseExited
        resetColor(btnAlterar);
    }//GEN-LAST:event_btnAlterarMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil_clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil_clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTable Tabela;
    private javax.swing.JPanel btnAlterar;
    private javax.swing.JPanel btnCancelar;
    private javax.swing.JPanel btnInformacoes;
    private javax.swing.JPanel btnNovoContrato;
    private javax.swing.JPanel btnPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNumeroContrato;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCPF;
    private static javax.swing.JLabel lblId;
    private javax.swing.JLabel lblNome;
    private javax.swing.JPanel painel_header;
    // End of variables declaration//GEN-END:variables
}
