/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import javax.swing.BorderFactory;
import javax.swing.JPanel;

/**
 *
 * @author Alexf
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public Principal() {
        initComponents();
        resetColor(painel_atendimento);
        resetColor(painel_canais);
        resetColor(painel_lista);
        resetColor(painel_sair);
        this.getRootPane().setBorder(BorderFactory.createMatteBorder(2, 2, 2, 2, Color.BLACK));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painel_principal = new javax.swing.JPanel();
        painel_header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        painel_sair = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        painel_lista = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        painel_atendimento = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        painel_canais = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painel_principal.setBackground(new java.awt.Color(255, 255, 255));
        painel_principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painel_header.setBackground(new java.awt.Color(45, 118, 232));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Painel de controle");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Tv Master");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/happy.png"))); // NOI18N

        javax.swing.GroupLayout painel_headerLayout = new javax.swing.GroupLayout(painel_header);
        painel_header.setLayout(painel_headerLayout);
        painel_headerLayout.setHorizontalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(862, Short.MAX_VALUE))
        );
        painel_headerLayout.setVerticalGroup(
            painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_headerLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(painel_headerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(painel_headerLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        painel_principal.add(painel_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 190));

        painel_sair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel_sairMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painel_sairMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painel_sairMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(45, 118, 232));
        jLabel3.setText("Sair");

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sair2.png"))); // NOI18N

        javax.swing.GroupLayout painel_sairLayout = new javax.swing.GroupLayout(painel_sair);
        painel_sair.setLayout(painel_sairLayout);
        painel_sairLayout.setHorizontalGroup(
            painel_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_sairLayout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(painel_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_sairLayout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_sairLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(65, 65, 65))))
        );
        painel_sairLayout.setVerticalGroup(
            painel_sairLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_sairLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        painel_principal.add(painel_sair, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 460, 170, 160));

        painel_lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel_listaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painel_listaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painel_listaMouseExited(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(45, 118, 232));
        jLabel10.setText("Clientes");

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente-grande.png"))); // NOI18N

        javax.swing.GroupLayout painel_listaLayout = new javax.swing.GroupLayout(painel_lista);
        painel_lista.setLayout(painel_listaLayout);
        painel_listaLayout.setHorizontalGroup(
            painel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_listaLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(painel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel16)
                    .addComponent(jLabel10))
                .addGap(34, 34, 34))
        );
        painel_listaLayout.setVerticalGroup(
            painel_listaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_listaLayout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(18, 18, 18))
        );

        painel_principal.add(painel_lista, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 270, 170, 160));

        painel_atendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                painel_atendimentoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painel_atendimentoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painel_atendimentoMouseExited(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/atendimento.png"))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(45, 118, 232));
        jLabel6.setText("Atendimento");

        javax.swing.GroupLayout painel_atendimentoLayout = new javax.swing.GroupLayout(painel_atendimento);
        painel_atendimento.setLayout(painel_atendimentoLayout);
        painel_atendimentoLayout.setHorizontalGroup(
            painel_atendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_atendimentoLayout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addGroup(painel_atendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6))
                .addGap(35, 35, 35))
        );
        painel_atendimentoLayout.setVerticalGroup(
            painel_atendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_atendimentoLayout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addContainerGap())
        );

        painel_principal.add(painel_atendimento, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, 170, 160));

        painel_canais.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painel_canaisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painel_canaisMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painel_canaisMousePressed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/canais.png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(45, 118, 232));
        jLabel12.setText("Canais");

        javax.swing.GroupLayout painel_canaisLayout = new javax.swing.GroupLayout(painel_canais);
        painel_canais.setLayout(painel_canaisLayout);
        painel_canaisLayout.setHorizontalGroup(
            painel_canaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painel_canaisLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(painel_canaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel15)
                    .addComponent(jLabel12))
                .addGap(34, 34, 34))
        );
        painel_canaisLayout.setVerticalGroup(
            painel_canaisLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painel_canaisLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addContainerGap())
        );

        painel_principal.add(painel_canais, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 170, 160));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1100, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painel_principal, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void painel_atendimentoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_atendimentoMouseEntered
        // TODO add your handling code here:
        setColor(painel_atendimento);
    }//GEN-LAST:event_painel_atendimentoMouseEntered

    private void painel_listaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_listaMouseEntered
        // TODO add your handling code here:
        setColor(painel_lista);
    }//GEN-LAST:event_painel_listaMouseEntered

    private void painel_canaisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_canaisMouseEntered
           setColor(painel_canais);
        // TODO add your handling code here:
    }//GEN-LAST:event_painel_canaisMouseEntered

    private void painel_sairMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_sairMouseEntered
        // TODO add your handling code here:
        setColor(painel_sair);
        
    }//GEN-LAST:event_painel_sairMouseEntered

    private void painel_atendimentoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_atendimentoMouseExited
        resetColor(painel_atendimento);
        // TODO add your handling code here:
    }//GEN-LAST:event_painel_atendimentoMouseExited

    private void painel_listaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_listaMouseExited
            // TODO add your handling code here:
            resetColor(painel_lista);
    }//GEN-LAST:event_painel_listaMouseExited

    private void painel_canaisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_canaisMouseExited
        resetColor(painel_canais);
        // TODO add your handling code here:
    }//GEN-LAST:event_painel_canaisMouseExited

    private void painel_sairMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_sairMouseExited
        // TODO add your handling code here:
        resetColor(painel_sair);
    }//GEN-LAST:event_painel_sairMouseExited

    private void painel_canaisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_canaisMousePressed
        new Canais().setVisible(true);
        
    }//GEN-LAST:event_painel_canaisMousePressed

    private void painel_listaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_listaMouseClicked
        new Clientes().setVisible(true);
    }//GEN-LAST:event_painel_listaMouseClicked

    private void painel_atendimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_atendimentoMouseClicked
        new Procura_contratos_chamado().setVisible(true);
    }//GEN-LAST:event_painel_atendimentoMouseClicked

    private void painel_sairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painel_sairMouseClicked
        dispose();
        new  Login().setVisible(true);
    }//GEN-LAST:event_painel_sairMouseClicked

    
    public void setColor(JPanel panel){
        panel.setBackground(new Color(204,204,204));
    }
    
    public void resetColor(JPanel panel){
        panel.setBackground(new Color(240,240,240));
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel painel_atendimento;
    private javax.swing.JPanel painel_canais;
    private javax.swing.JPanel painel_header;
    private javax.swing.JPanel painel_lista;
    private javax.swing.JPanel painel_principal;
    private javax.swing.JPanel painel_sair;
    // End of variables declaration//GEN-END:variables
}
